// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/store": {
    params: {};
  };
  "/readyz": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blog" | "/store" | "/readyz";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/blog.tsx": {
    id: "routes/blog";
    page: "/blog";
  };
  "./routes/store.tsx": {
    id: "routes/store";
    page: "/store";
  };
  "./routes/readyz.ts": {
    id: "routes/readyz";
    page: "/readyz";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "routes/blog": typeof import("./app/./routes/blog.tsx");
  "routes/store": typeof import("./app/./routes/store.tsx");
  "routes/readyz": typeof import("./app/./routes/readyz.ts");
};