export const COUNTRIES: readonly string[] = [
  'Romania',
  'Austria',
  'Belgium',
  'Bulgaria',
  'Czechia',
  'Denmark',
  'France',
  'Germany',
  'Greece',
  'Hungary',
  'Ireland',
  'Italy',
  'Moldova',
  'Netherlands',
  'Poland',
  'Portugal',
  'Spain',
  'Sweden',
  'Switzerland',
  'United Kingdom',
  'United States',
];
