packages:
  - apps/*
  - packages/*

catalog:
  "@react-router/dev": 7.13.2
  "@react-router/node": 7.13.2
  "@react-router/serve": 7.13.2
  "@types/node": 22.19.15
  "@types/pg": 8.20.0
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  esbuild: 0.27.4
  fastify: 5.8.4
  isbot: 5.1.36
  pg: 8.20.0
  react: 19.2.4
  react-dom: 19.2.4
  react-router: 7.13.2
  tsx: 4.21.0
  typescript: 5.9.3
  vite: 8.0.3
  zod: 4.3.6

cleanupUnusedCatalogs: true
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build

allowBuilds:
  esbuild: true
