CREATE TABLE "app"."exercises" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(120) NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"difficulty" varchar(16) NOT NULL,
	"equipment" text[] DEFAULT '{}'::text[] NOT NULL,
	"primary_muscles" text[] DEFAULT '{}'::text[] NOT NULL,
	"secondary_muscles" text[] DEFAULT '{}'::text[] NOT NULL,
	"tags" text[] DEFAULT '{}'::text[] NOT NULL,
	"video_asset_key" varchar(512),
	"video_mime_type" varchar(255),
	"video_size_bytes" integer,
	"video_sha256" varchar(64),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "exercises_name_check" CHECK (length(btrim("app"."exercises"."name")) > 0),
	CONSTRAINT "exercises_difficulty_check" CHECK ("app"."exercises"."difficulty" in ('Beginner', 'Intermediate', 'Advanced')),
	CONSTRAINT "exercises_equipment_check" CHECK ("app"."exercises"."equipment" <@ array['Barbell', 'Dumbbells', 'Kettlebell', 'Machine', 'Cable', 'Bands', 'Bodyweight', 'Bench']::text[]),
	CONSTRAINT "exercises_primary_muscles_check" CHECK ("app"."exercises"."primary_muscles" <@ array['Chest', 'Back', 'Shoulders', 'Quadriceps', 'Hamstrings', 'Glutes', 'Calves', 'Core', 'Biceps', 'Triceps']::text[]),
	CONSTRAINT "exercises_secondary_muscles_check" CHECK ("app"."exercises"."secondary_muscles" <@ array['Chest', 'Back', 'Shoulders', 'Quadriceps', 'Hamstrings', 'Glutes', 'Calves', 'Core', 'Biceps', 'Triceps']::text[]),
	CONSTRAINT "exercises_muscles_disjoint_check" CHECK (not ("app"."exercises"."primary_muscles" && "app"."exercises"."secondary_muscles")),
	CONSTRAINT "exercises_tags_check" CHECK ("app"."exercises"."tags" <@ array['Strength', 'Hypertrophy', 'Recovery']::text[]),
	CONSTRAINT "exercises_video_presence_check" CHECK (("app"."exercises"."video_asset_key" is null and "app"."exercises"."video_mime_type" is null and "app"."exercises"."video_size_bytes" is null and "app"."exercises"."video_sha256" is null) or ("app"."exercises"."video_asset_key" is not null and "app"."exercises"."video_mime_type" is not null and "app"."exercises"."video_size_bytes" is not null and "app"."exercises"."video_sha256" is not null)),
	CONSTRAINT "exercises_video_relative_key_check" CHECK ("app"."exercises"."video_asset_key" is null or (length(btrim("app"."exercises"."video_asset_key")) > 0 and "app"."exercises"."video_asset_key" !~ '(^/|(^|/)\.\.(/|$))' and position(chr(92) in "app"."exercises"."video_asset_key") = 0 and "app"."exercises"."video_asset_key" !~ '^[A-Za-z]:')),
	CONSTRAINT "exercises_video_size_check" CHECK ("app"."exercises"."video_size_bytes" is null or "app"."exercises"."video_size_bytes" >= 0),
	CONSTRAINT "exercises_video_sha256_check" CHECK ("app"."exercises"."video_sha256" is null or "app"."exercises"."video_sha256" ~ '^[0-9a-f]{64}$')
);
