FROM node:22-bookworm-slim

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN corepack enable

WORKDIR /workspace

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json .npmrc ./
COPY apps ./apps
COPY packages ./packages

ARG APP_DIR

RUN pnpm install --frozen-lockfile

ENV NODE_ENV=production

WORKDIR /workspace/$APP_DIR

CMD ["pnpm", "start"]
