ARG POSTGRES_IMAGE=postgres:18.3-bookworm@sha256:80630f83606d8db77d30b3851b16a9f78be2d0d4dda6f7b82a1fdca5ebe3acba

FROM ${POSTGRES_IMAGE}

RUN set -eux; \
  apt-get update; \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --only-upgrade \
    libc-bin \
    libc-l10n \
    libc6 \
    libcap2 \
    libgnutls30 \
    libgssapi-krb5-2 \
    libk5crypto3 \
    libkrb5-3 \
    libkrb5support0 \
    libperl5.36 \
    libpcre2-8-0 \
    libssl3 \
    libsystemd0 \
    libudev1 \
    locales \
    openssl \
    perl \
    perl-base \
    perl-modules-5.36; \
  rm -rf /var/lib/apt/lists/*
